/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Fifth.glb 
*/

import React, { useMemo } from "react";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Fifth.glb");
  const newMaterials = useMemo(
    () => convertMaterialsToBasic(materials),
    [materials]
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Fifth_Decorative_Stuff_Baked.geometry}
        material={newMaterials.Fifth_Baked}
        position={[19.576, 8.488, -28.211]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
