/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ninth.glb 
*/

import React, { useEffect, useState, useMemo, useRef } from "react";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";
import * as THREE from "three";
import { useModalStore } from "../../stores/useModalStore";
import { useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

// Default dimensions (Width x Height) - change these values anytime!
const EMBLEM_WIDTH = 1.6;
const EMBLEM_HEIGHT = 2.1;

const WallEmblemItem = ({
  id,
  title,
  texturePath,
  position,
  width = EMBLEM_WIDTH,
  height = EMBLEM_HEIGHT,
  progress,
  pulseIntensity,
  isModalOpen,
  hoveredMesh,
  setHoveredMesh,
  handleClick,
}) => {
  const texture = useTexture(texturePath);
  const isHovered = hoveredMesh === id;
  const isInteractable = progress >= 0.399 && progress <= 0.6 && !isModalOpen;

  const groupRef = useRef();

  useFrame((_, delta) => {
    if (!groupRef.current) return;
    // Target position z offset for hover exposure off the wall
    const targetZ = isHovered && isInteractable ? position[2] + 0.18 : position[2];
    groupRef.current.position.z = THREE.MathUtils.lerp(
      groupRef.current.position.z,
      targetZ,
      delta * 8
    );
  });

  const goldGlowColor = useMemo(() => {
    const pulse = 1 + pulseIntensity * 0.8;
    return isHovered
      ? "#ffe082"
      : `rgb(${Math.floor(180 * pulse)}, ${Math.floor(140 * pulse)}, ${Math.floor(70 * pulse)})`;
  }, [isHovered, pulseIntensity]);

  return (
    <group
      ref={groupRef}
      position={[position[0], position[1], position[2]]}
      onPointerOver={(e) => {
        e.stopPropagation();
        if (isInteractable) setHoveredMesh(id);
      }}
      onPointerOut={(e) => {
        e.stopPropagation();
        setHoveredMesh(null);
      }}
      onClick={(e) => {
        e.stopPropagation();
        if (isInteractable) handleClick(id);
      }}
    >
      {/* 3D Dark Obsidian Stone Backing Plaque (Stuck to wall, exposing depth) */}
      <mesh position={[0, 0, -0.05]}>
        <boxGeometry args={[width + 0.08, height + 0.08, 0.12]} />
        <meshStandardMaterial
          color={isHovered ? "#26221c" : "#141312"}
          roughness={0.8}
          metalness={0.4}
        />
      </mesh>

      {/* 3D Dark Gold Metallic Beveled Border Frame */}
      <mesh position={[0, 0, 0]}>
        <boxGeometry args={[width + 0.14, height + 0.14, 0.06]} />
        <meshStandardMaterial
          color={goldGlowColor}
          roughness={0.3}
          metalness={0.85}
          emissive={isHovered ? "#ffaa00" : "#332200"}
          emissiveIntensity={isHovered ? 0.65 : 0.15}
        />
      </mesh>

      {/* Front Textured Emblem Relief Face */}
      <mesh position={[0, 0, 0.04]}>
        <planeGeometry args={[width, height]} />
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  );
};

/*
 * ── Event poster placement ──────────────────────────────────────────────────
 * Measured directly out of public/models/Ninth.glb (draco-decoded), node
 * "Ninth_Paper_Baked" at translation [6.122460, 6.807644, -35.966049].
 * The sheet of paper lying on the desk is the topmost inclined quad in that
 * mesh, and it measures:
 *
 *   world centre  : [6.122251, 8.194515, -35.937829]
 *   surface normal: [0, 0.954588, 0.297928]   → 17.33° off horizontal
 *   in-plane size : 0.271675 wide × 0.369273 tall  (aspect 0.7357)
 *
 * Rotating the group by PAPER_ROTATION_X about X lines its local +Z up with
 * that normal, so the poster lies exactly in the plane of the page and a local
 * +Z offset lifts it straight off the paper.
 */
const PAPER_CENTER = [6.122251, 8.194515, -35.937829];
const PAPER_ROTATION_X = -1.268275; // radians (-72.667°)
const PAPER_WIDTH = 0.271675;
const PAPER_HEIGHT = 0.369273;

// Event posters are 1587 × 2245 (aspect 0.7069), very slightly narrower than
// the page. Fit it to the page's full height and inset proportionally rather
// than stretching it wide to fill the paper edge to edge. To fill the
// page exactly instead, use PAPER_WIDTH / PAPER_HEIGHT here.
const POSTER_HEIGHT = PAPER_HEIGHT;
const POSTER_WIDTH = Math.min(PAPER_WIDTH, PAPER_HEIGHT * (1587 / 2245));

// Clearance above the page, measured along the page normal.
const POSTER_REST_LIFT = 0.0012;
const POSTER_HOVER_LIFT = 0.006;

const TableTopPoster = ({ progress, isModalOpen, onClick }) => {
  const posterTexture = useTexture("/textures/event_poster.png");
  const [hovered, setHovered] = useState(false);
  const meshRef = useRef();

  useMemo(() => {
    posterTexture.colorSpace = THREE.SRGBColorSpace;
    posterTexture.anisotropy = 16;
    posterTexture.needsUpdate = true;
  }, [posterTexture]);

  // The camera sweeps over the desk between these two points on the curve.
  const isInteractable = progress >= 0.2 && progress <= 0.36 && !isModalOpen;
  const isHovered = hovered && isInteractable;

  useEffect(() => {
    if (!isHovered) return;
    document.body.style.cursor = "pointer";

    return () => {
      document.body.style.cursor = "auto";
    };
  }, [isHovered]);

  useFrame((_, delta) => {
    if (!meshRef.current) return;
    meshRef.current.position.z = THREE.MathUtils.lerp(
      meshRef.current.position.z,
      isHovered ? POSTER_HOVER_LIFT : POSTER_REST_LIFT,
      delta * 8
    );
  });

  return (
    <group position={PAPER_CENTER} rotation={[PAPER_ROTATION_X, 0, 0]}>
      <mesh
        ref={meshRef}
        position={[0, 0, POSTER_REST_LIFT]}
        onPointerOver={(e) => {
          e.stopPropagation();
          if (isInteractable) setHovered(true);
        }}
        onPointerOut={(e) => {
          e.stopPropagation();
          setHovered(false);
        }}
        onClick={(e) => {
          e.stopPropagation();
          if (isInteractable && onClick) onClick();
        }}
      >
        <planeGeometry args={[POSTER_WIDTH, POSTER_HEIGHT]} />
        <meshBasicMaterial
          map={posterTexture}
          color={isHovered ? "#ffffff" : "#e8e2d6"}
          side={THREE.DoubleSide}
          toneMapped={false}
          polygonOffset
          polygonOffsetFactor={-2}
          polygonOffsetUnits={-2}
        />
      </mesh>
    </group>
  );
};

export default function Model({ progress = 0, pulseIntensity = 0, ...props }) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Ninth.glb");
  const [hoveredMesh, setHoveredMesh] = useState(null);
  const { openModal, setModalID, isModalOpen } = useModalStore();

  const newMaterials = useMemo(
    () => convertMaterialsToBasic(materials),
    [materials]
  );

  useEffect(() => {
    if (progress <= 0.399 || progress >= 0.6 || isModalOpen) return;
    document.body.style.cursor = hoveredMesh ? "pointer" : "auto";

    return () => {
      document.body.style.cursor = "auto";
    };
  }, [hoveredMesh, progress, isModalOpen]);

  const handleClick = (elementID) => {
    if (progress <= 0.399 || progress >= 0.6 || isModalOpen) return;
    openModal();
    setModalID(elementID);
  };

  const handlePosterClick = () => {
    openModal();
    setModalID("events");
  };

  const emblemItems = useMemo(
    () => [
      {
        id: "dashboard",
        title: "DASHBOARD",
        texturePath: "/textures/valyria_about.png",
        position: [-0.457, 9.285, -48.4],
      },
      {
        id: "events",
        title: "EVENTS",
        texturePath: "/textures/valyria_events.png",
        position: [2.778, 9.285, -48.4],
      },
      {
        id: "schedule",
        title: "SCHEDULE",
        texturePath: "/textures/valyria_schedule.png",
        position: [6.136, 9.285, -48.4],
      },
      {
        id: "staff_coordinators",
        title: "STAFF COORDINATORS",
        texturePath: "/textures/valyria_staff.png",
        position: [9.538, 9.285, -48.4],
      },
      {
        id: "zyverse_team",
        title: "ZYVERSE TEAM",
        texturePath: "/textures/valyria_team.png",
        position: [12.806, 9.285, -48.4],
      },
    ],
    []
  );

  return (
    <group {...props} dispose={null}>
      {emblemItems.map((item) => (
        <WallEmblemItem
          key={item.id}
          id={item.id}
          title={item.title}
          texturePath={item.texturePath}
          position={item.position}
          progress={progress}
          pulseIntensity={pulseIntensity}
          isModalOpen={isModalOpen}
          hoveredMesh={hoveredMesh}
          setHoveredMesh={setHoveredMesh}
          handleClick={handleClick}
        />
      ))}
      {/* 3D Wooden Lectern Stand with authentic textures */}
      <mesh
        geometry={nodes.Ninth_Paper_Baked.geometry}
        material={newMaterials["Ninth_real_actual_Baked"]}
        position={[6.122, 6.808, -35.966]}
      />
      {/* Event poster lying on the sheet of paper on the desk */}
      <TableTopPoster
        progress={progress}
        isModalOpen={isModalOpen}
        onClick={handlePosterClick}
      />
    </group>
  );
}
