/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Sixth.glb 
*/

import React, { useMemo } from "react";
import { useGLTFWithKTX2 } from "../utils/useGLTFWithKTX2";
import { convertMaterialsToBasic } from "../utils/convertToBasic";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2("/models/Sixth.glb");
  const newMaterials = useMemo(
    () => convertMaterialsToBasic(materials),
    [materials]
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sixth_Walls_Baked.geometry}
        material={newMaterials.Sixth_Baked}
        position={[4.568, 6.749, -38.719]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  );
}
